version: '3.8'

services:
  storyweaver:
    image: storyweaver:latest
    container_name: storyweaver-prod
    
    # Restart Policy
    restart: unless-stopped
    
    # Port Mapping - für Reverse Proxy intern
    expose:
      - "8501"
    
    # Für direkten Zugriff (ohne Reverse Proxy)
    # ports:
    #   - "8501:8501"
    
    # Environment Variablen
    environment:
      - STREAMLIT_THEME=${STREAMLIT_THEME:-Dark}
      - PROJECT_NAME=${PROJECT_NAME:-StoryWeaver}
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
      # Produktions-spezifisch
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=none
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    
    # Volumes für Produktion (nur Daten, kein Code)
    volumes:
      # Persistente Daten
      - ./input:/app/input
      - ./output:/app/output
      - ./assets:/app/assets
      - ./examples:/app/examples:ro
      - streamlit_uploads:/app/streamlit_uploads
      
      # spaCy Model Cache
      - spacy_models:/root/.cache/spacy
    
    # Netzwerk
    networks:
      - storyweaver-network
      - proxy-network  # Für Reverse Proxy
    
    # Resource Limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    
    # Labels für Reverse Proxy (Traefik Beispiel)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storyweaver.rule=Host(`storyweaver.example.com`)"
      - "traefik.http.routers.storyweaver.entrypoints=websecure"
      - "traefik.http.routers.storyweaver.tls.certresolver=letsencrypt"
      - "traefik.http.services.storyweaver.loadbalancer.server.port=8501"

# Optional: Nginx Reverse Proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: storyweaver-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - storyweaver
  #   networks:
  #     - storyweaver-network

# Benannte Volumes
volumes:
  streamlit_uploads:
    name: storyweaver_uploads
  spacy_models:
    name: storyweaver_spacy_cache

# Netzwerke
networks:
  storyweaver-network:
    name: storyweaver_net
    driver: bridge
  proxy-network:
    external: true
    name: proxy_network 